name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@Breiby'
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - name: Print time
        id: print
        run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
